# Generated by Django 4.2.20 on 2025-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when this log record was created.",
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        blank=True,
                        help_text="An optional identifier for the user who made the request.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        help_text="A unique thread ID that identifies a conversation.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="The AI model name, e.g., 'gpt-4o' or 'gpt-4o-mini'.",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="The temperature setting used for this request."
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The prompt text sent by the user."),
                ),
                (
                    "ai_response",
                    models.TextField(
                        blank=True,
                        help_text="The full response from the OpenAI model.",
                        null=True,
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        help_text="The stop reason returned by the AI, if any.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Details of any error encountered during the request.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
